services:
  ollama:
    image: ollama/ollama:latest
    container_name: lexigrade-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./llm-models:/models
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    entrypoint: ["/bin/bash", "/ollama-entrypoint.sh"]
    restart: unless-stopped
volumes:
  ollama_data:
